<!DOCTYPE html>
<html lang="fr" class="h-100">
<!-- HEAD -->
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Live Messenger</title>
    <link rel="stylesheet" href="./assets/reset.css">
    <link rel="stylesheet" href="./assets/style.css">
</head>

<!-- BODY -->
<body class="d-flex flex-column h-100">
    <!-- HEADER START -->
    <header>
    </header>
    <!-- HEADER END -->

    <!-- MAIN START -->
    <main class="flex-shrink-0">
    <?php
        include "./views/template_".$page.".phtml";
    ?>
    </main>
    <!-- MAIN END -->

    <!-- FOOTER START -->
    <footer class="">

    </footer>
    <!-- FOOTER END -->

    <script src="https://code.iconify.design/iconify-icon/1.0.8/iconify-icon.min.js"></script>
</body>
</html>